m1: 3
m2: 12
m3: 10
party_mnemonic: "minimum law tackle eager asset energy true stove human sock comic autumn brass rib harsh mobile ivory inspire stool reopen deny repair spirit above imitate"
client_mnemonic: "rally loyal price fashion disease rain zoo indicate until gentle ahead trap view observe index deer used space copper talent way old patient abandon simple"